# Template from: https://goreleaser.com/customization/build/
builds:
  - main: ./src/main.go

    # GOOS list to build for.
    # For more info refer to: https://golang.org/doc/install/source#environment
    goos:
      - linux
      - darwin
      - windows

    # GOARCH to build for.
    # For more info refer to: https://golang.org/doc/install/source#environment
    goarch:
      - amd64
      - arm
      - arm64
      - '386'

archives:
  - format: binary
    name_template: '{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}'
    replacements:
      darwin: macOS

dockers:
  - image_templates:
      - 'ghcr.io/amrsaber/redirector:{{ .Tag }}'
      - 'ghcr.io/amrsaber/redirector:v{{ .Major }}'
      - 'ghcr.io/amrsaber/redirector:v{{ .Major }}.{{ .Minor }}'
      - 'ghcr.io/amrsaber/redirector:latest'
