# Template from: https://goreleaser.com/customization/build/
project_name: redirector

builds:
  - main: ./src/main.go

    env:
      - CGO_ENABLED=0

    # GOOS list to build for.
    # For more info refer to: https://golang.org/doc/install/source#environment
    goos:
      - linux
      - darwin

    # GOARCH to build for.
    # For more info refer to: https://golang.org/doc/install/source#environment
    goarch:
      - amd64
      - arm
      - arm64
      - '386'

archives:
  - format: binary
    name_template: '{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}'

dockers:
  - dockerfile: goreleaser.dockerfile
    goos: linux
    goarch: amd64
    image_templates:
      - 'ghcr.io/amrsaber/{{ .ProjectName }}:{{ .Tag }}'
      - 'ghcr.io/amrsaber/{{ .ProjectName }}:v{{ .Major }}.{{ .Minor }}'
      - 'ghcr.io/amrsaber/{{ .ProjectName }}:v{{ .Major }}'
      - 'ghcr.io/amrsaber/{{ .ProjectName }}:latest'
